export const data = [
  {
    image: "/images/one.jpeg",
    title: "Vintage Crepe",
    price: "2500",
    discount: "-15",
    ratings: "3",
    shipping: "free",
  },
  {
    image: "/images/two.jpeg",
    title: "Vintage Crepe",
    price: "2500",
    discount: "-15",
    ratings: "3",
    shipping: "free",
  },
  {
    image: "/images/three.jpeg",
    title: "Vintage Crepe",
    price: "2500",
    discount: "-15",
    ratings: "3",
    shipping: "free",
  },
  {
    image: "/images/four.jpeg",
    title: "Vintage Crepe",
    price: "2500",
    discount: "-15",
    ratings: "3",
    shipping: "free",
  },
  {
    image: "/images/five.jpeg",
    title: "Vintage Crepe",
    price: "2500",
    discount: "-15",
    ratings: "3",
    shipping: "free",
  },
  {
    image: "/images/six.jpeg",
    title: "Vintage Crepe",
    price: "2500",
    discount: "-15",
    ratings: "3",
    shipping: "free",
  },
  {
    image: "/images/seven.jpeg",
    title: "Vintage Crepe",
    price: "2500",
    discount: "-15",
    ratings: "3",
    shipping: "free",
  },
  {
    image: "/images/eight.jpeg",
    title: "Vintage Crepe",
    price: "2500",
    discount: "-15",
    ratings: "3",
    shipping: "free",
  },
  {
    image: "/images/nine.jpeg",
    title: "Vintage Crepe",
    price: "2500",
    discount: "-15",
    ratings: "3",
    shipping: "free",
  },
];
