const { v4: uuidv4 } = require("uuid");

export const data = [
  {
    id: uuidv4(),
    image: "/images/one.jpeg",
    title: "Cotton",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/two.jpeg",
    title: "Linen",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/three.jpeg",
    title: "Silk",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/four.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/five.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/six.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/seven.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/eight.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/nine.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/two.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/three.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/four.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/five.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/one.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/two.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/three.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/four.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/five.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/six.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/seven.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/eight.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/nine.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/two.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/three.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/four.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
  {
    id: uuidv4(),
    image: "/images/five.jpeg",
    title: "Vintage Crepe",
    price: 2500,
    discount: "-15",
    ratings: "3",
    shipping: "free",
    categories: "vintage crepe",
    colors: ["yellow", "red", "orange", "blue", "violet"],
    images: [
      "/images/one.jpeg",
      "/images/two.jpeg",
      "/images/three.jpeg",
      "/images/four.jpeg",
      "/images/five.jpeg",
    ],
  },
];
